name: UnitTests Check

on:
  pull_request:
    branches:
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Unit Tests Check
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
