name: UnitTests Check

on:
  pull_request:
    branches:
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
